version: "3.6"

services:
  #Backend
  smartbrain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-api
    environment:
      POSTGRES_URI: postgres://imwxjwntilnoga:$PG_PWD@postgres:5432/smartbrain-docker
      API_KEY: $CLARIFAI_API_KEY
      PORT: 80
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/smartbrain-api
    #Postgres
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: smartbrain-docker
      POSTGRES_USER: imwxjwntilnoga
      POSTGRES_PASSWORD: $PG_PWD
    build: ./postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
